
# This file controls the behavior of Supabase Edge Functions.

project_id = "mjqbyxrvonhekukzkjhd"

[functions.ai-chat]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false
