// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjqbyxrvonhekukzkjhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcWJ5eHJ2b25oZWt1a3pramhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDI2OTEsImV4cCI6MjA2MDcxODY5MX0.zcW-yxlCmpUcCE8T1qTNtdYjeYox1KwHWvltf6ivv-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);